package com.credan.webapi.core.dao.entity.merchant;

import java.math.BigDecimal;

import com.credan.webapi.core.dao.entity.BasicEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = false)
public class MerchantCashLoanApply extends BasicEntity {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.order_id
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String orderId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.merchanrt_id
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String merchanrtId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.token
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String token;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.user_id
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.source
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String source;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.apply_amount
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private BigDecimal applyAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.apply_term
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private Long applyTerm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.term_unit
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String termUnit;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_cash_loan_apply.ext
	 *
	 * @mbg.generated Mon Nov 21 11:47:43 CST 2016
	 */
	private String ext;

}