package com.credan.webapi.core.dao.entity.merchant;

import java.math.BigDecimal;

import com.credan.webapi.core.dao.entity.BasicEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = false)
public class MerchantInfo extends BasicEntity {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.reg_name
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String regName;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.name
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.owner
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String owner;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.address
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String address;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.code
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String code;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.city
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String city;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.status
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_merchant.longitude
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String longitude;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.latitude
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String latitude;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_merchant.parent_id
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String parentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.level
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private Integer level;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_merchant.max_amount
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private BigDecimal maxAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ci_merchant.phone
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String phone;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_merchant.bank_card_no
	 *
	 * @mbg.generated Mon Nov 07 19:10:05 CST 2016
	 */
	private String bankCardNo;

}