package com.credan.webapi.core.dao.entity.order;

import java.math.BigDecimal;

import com.credan.webapi.core.dao.entity.BasicEntity;

public class OrderDetailLog extends BasicEntity {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.merchant_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String merchantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.order_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String orderId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.name
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.type
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String type;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.price
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private BigDecimal price;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.order_amount
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private BigDecimal orderAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.term
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private Long term;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.unit
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String unit;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.count
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private Long count;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.desc
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String desc;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.ext
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String ext;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.merchant_id
	 *
	 * @return the value of merchant_order_detail_log.merchant_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getMerchantId() {
		return merchantId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.merchant_id
	 *
	 * @param merchantId the value for merchant_order_detail_log.merchant_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId == null ? null : merchantId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.order_id
	 *
	 * @return the value of merchant_order_detail_log.order_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.order_id
	 *
	 * @param orderId the value for merchant_order_detail_log.order_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setOrderId(String orderId) {
		this.orderId = orderId == null ? null : orderId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.name
	 *
	 * @return the value of merchant_order_detail_log.name
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.name
	 *
	 * @param name the value for merchant_order_detail_log.name
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.type
	 *
	 * @return the value of merchant_order_detail_log.type
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.type
	 *
	 * @param type the value for merchant_order_detail_log.type
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setType(String type) {
		this.type = type == null ? null : type.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.price
	 *
	 * @return the value of merchant_order_detail_log.price
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.price
	 *
	 * @param price the value for merchant_order_detail_log.price
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.order_amount
	 *
	 * @return the value of merchant_order_detail_log.order_amount
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public BigDecimal getOrderAmount() {
		return orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.order_amount
	 *
	 * @param orderAmount the value for merchant_order_detail_log.order_amount
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.term
	 *
	 * @return the value of merchant_order_detail_log.term
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public Long getTerm() {
		return term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.term
	 *
	 * @param term the value for merchant_order_detail_log.term
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setTerm(Long term) {
		this.term = term;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.unit
	 *
	 * @return the value of merchant_order_detail_log.unit
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getUnit() {
		return unit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.unit
	 *
	 * @param unit the value for merchant_order_detail_log.unit
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.count
	 *
	 * @return the value of merchant_order_detail_log.count
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public Long getCount() {
		return count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.count
	 *
	 * @param count the value for merchant_order_detail_log.count
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setCount(Long count) {
		this.count = count;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.desc
	 *
	 * @return the value of merchant_order_detail_log.desc
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getDesc() {
		return desc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.desc
	 *
	 * @param desc the value for merchant_order_detail_log.desc
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setDesc(String desc) {
		this.desc = desc == null ? null : desc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column
	 * merchant_order_detail_log.ext
	 *
	 * @return the value of merchant_order_detail_log.ext
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public String getExt() {
		return ext;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column
	 * merchant_order_detail_log.ext
	 *
	 * @param ext the value for merchant_order_detail_log.ext
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	public void setExt(String ext) {
		this.ext = ext == null ? null : ext.trim();
	}

}