package com.credan.webapi.core.dao.entity.order;

import java.math.BigDecimal;

import com.credan.webapi.core.dao.entity.BasicEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = false)
public class OrderDetailLog extends BasicEntity {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.merchant_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String merchantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.order_id
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String orderId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.name
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.type
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String type;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.price
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private BigDecimal price;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.order_amount
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private BigDecimal orderAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.term
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private Long term;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.unit
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String unit;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.count
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private Long count;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.desc
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String remarks;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail_log.ext
	 *
	 * @mbg.generated Thu Nov 03 11:34:05 CST 2016
	 */
	private String ext;
	
	private String userId;
	private String token;
	private String source;

}