package com.credan.webapi.core.dao.entity.order;

import java.math.BigDecimal;
import java.util.Date;

import com.credan.webapi.core.dao.entity.BasicEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper =false)
public class OrderDetail extends BasicEntity {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.merchant_id
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String merchantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.order_id
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String orderId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.project_id
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String projectId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.name
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String name;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.type
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String type;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.price
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private BigDecimal price;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.order_amount
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private BigDecimal orderAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.term
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private Long term;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.unit
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String unit;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.count
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private Long count;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.desc
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String remarks;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.call_back_time
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private Date callBackTime;
	
	private Date nextCallBackTime;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.call_back_count
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private Long callBackCount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.call_back_result
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String callBackResult;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.ext
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private String ext;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * merchant_order_detail.version
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	private Long version;

}