package com.credan.webapi.core.dao.entity.sys;

import lombok.Data;

@Data
public class SysDictionary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.id
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_type
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private String dictType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_name
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private String dictName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.dict_code
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private String dictCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.rank
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private Integer rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.parent_id
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dictionary.memo
     *
     * @mbg.generated Tue Nov 08 21:47:32 CST 2016
     */
    private String memo;
}