package com.credan.webapi.core.dao.entity.file;

import com.credan.webapi.core.dao.entity.BasicEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = false)
public class FileInfo extends BasicEntity{

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_type
     *
     * @mbg.generated Tue Nov 08 10:05:19 CST 2016
     */
    private String fileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.old_filename
     *
     * @mbg.generated Tue Nov 08 10:05:19 CST 2016
     */
    private String oldFilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.filename
     *
     * @mbg.generated Tue Nov 08 10:05:19 CST 2016
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file_info.file_path
     *
     * @mbg.generated Tue Nov 08 10:05:19 CST 2016
     */
    private String filePath;

}