/**
 * @(#) MyBatisDao.java
 * 
 * Copyright (c) 2016, Credan(上海)-版权所有
 * 
 */
package com.credan.webapi.config.mybatis.conf;

/**
 * 继承自己的MyBatisDao
 * 
 * @author Mond
 * @version 1.0.0, $Date: 2016年11月1日 下午6:56:39 $
 */
public interface MyBatisDao<T> {

	/**
	 * This method was generated by MyBatis Generator.
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	int insert(T record);

	/**
	 * This method was generated by MyBatis Generator.
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	int insertSelective(T record);

	/**
	 * This method was generated by MyBatis Generator.
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	T selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator.
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	int updateByPrimaryKeySelective(T record);

	/**
	 * This method was generated by MyBatis Generator.
	 *
	 * @mbg.generated Wed Nov 02 17:31:16 CST 2016
	 */
	int updateByPrimaryKey(T record);

}
