package com.credan.webapi.core.dao.entity.ci;

import java.math.BigDecimal;
import java.util.Date;

import com.credan.webapi.core.dao.entity.BasicEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = false)
public class InstallmentProject extends BasicEntity {

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.user_id
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String userId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.order_amount
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private BigDecimal orderAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.installment_amount
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private BigDecimal installmentAmount;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.term
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private Integer term;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.monthly_repay
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private BigDecimal monthlyRepay;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.monthly_fee
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private BigDecimal monthlyFee;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.daily_fee
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private BigDecimal dailyFee;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.next_term
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private Integer nextTerm;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.next_repayday
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String nextRepayday;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.audit_status
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String auditStatus;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.audit_date
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private Date auditDate;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.status
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String status;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.overdue_day
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private Integer overdueDay;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.description
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String description;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.merchant_id
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String merchantId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.agent_id
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private String agentId;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the database column
	 * ci_installment_project.product_code
	 *
	 * @mbg.generated Tue Nov 08 17:38:14 CST 2016
	 */
	private Integer productCode;

}